// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using NumberMachine.Models;
using System;

namespace NumberMachine.Migrations
{
    [DbContext(typeof(NumberMachineContext))]
    [Migration("20180213224528_AddNumberOutput")]
    partial class AddNumberOutput
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NumberMachine.Models.NumberInput", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("M");

                    b.Property<int>("N");

                    b.HasKey("ID");

                    b.ToTable("NumberInput");
                });

            modelBuilder.Entity("NumberMachine.Models.NumberOutput", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InputID");

                    b.Property<int>("Operation");

                    b.Property<int>("Output");

                    b.HasKey("ID");

                    b.HasIndex("InputID");

                    b.ToTable("NumberOutput");
                });

            modelBuilder.Entity("NumberMachine.Models.NumberOutput", b =>
                {
                    b.HasOne("NumberMachine.Models.NumberInput", "Input")
                        .WithMany()
                        .HasForeignKey("InputID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
